### ISSUE TITLE
The error from server should be readable.

### ISSUE THREAD

**Issue by WingGao** [snazysam/node-rtorrent-client#2]
https://github.com/snazysam/node-rtorrent-client/blob/dd7fd6d8b3ee56b87a7029118738adb432dae70f/lib/deserializer.ts#L188

I only get the output like this `Error: Failed to send command: Failed to execute method: [object Object]`, and cannot handle it in my catch case.

**Comment by snazysam** [comment]
Should be fixed with #3 

Will publish update to npm shortly
